successfull pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -221,128 +221,152 @@ jobs:
             ansible-playbook -i inventory.txt configure-server.yml
 
       - destroy-environment
-#       # Here's where you will add some code to rollback on failure      
+      # Here's where you will add some code to rollback on failure      
 
-#   run-migrations:
-#     docker:
-#       - image: cimg/node:13.8.0
-#     steps:
-#       - checkout
-#       - install_cli
-#       - run:
-#           name: Run migrations
-#           command: |
-#             cd backend
-#             npm install
-#             npm run migrations > migrations_dump.txt
-#       - run:
-#           name: Send migration status to kvdb.io
-#           command: |
-#             if grep -q "has been executed successfully" ~/project/backend/migrations_dump.txt
-#             then
-#               curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-#             fi  
-#       - destroy-environment
-#       - revert-migrations
+  run-migrations:
+    docker:
+      - image: cimg/node:13.8.0
+    steps:
+      - checkout
+      - install_cli
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+      - run:
+          name: Send migration status to kvdb.io
+          command: |
+            if grep -q "has been executed successfully" ~/project/backend/migrations_dump.txt
+            then
+              curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            fi  
+      - destroy-environment
+      - revert-migrations
 #      # Here's where you will add some code to rollback on failure      
 
-#   deploy-frontend:
-#     docker:
-#       - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_cli
-#       - install_nodejs
-#       - restore_cache:
-#           keys: [backend-dependencies-ck]
-#       - run:
-#           name: Install dependencies
-#           command: |
-#            cd frontend
-#            npm install
-#       - run:
-#           name: Get backend url
-#           command: |
-#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-#               --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#               --output text)
+  deploy-frontend:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_cli
+      - install_nodejs
+      - restore_cache:
+          keys: [backend-dependencies-ck]
+      - run:
+          name: Install dependencies
+          command: |
+           cd frontend
+           npm install
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
 
-#               echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
-#               cat frontend/.env
-#       - run:
-#           name: Deploy frontend objects
-#           command: |
-#             cd frontend
-#             npm run build
-#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-#       - destroy-environment
-#       - revert-migrations
+              echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
+              cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm run build
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - destroy-environment
+      - revert-migrations
 
                     
-#   deploy-backend:
-#     docker:
-#       - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_cli
-#       - install_ansible
-#       - install_nodejs
-#       - add_ssh_keys:
-#           fingerprints: ["3a:ac:7e:58:7d:53:2e:b4:b0:5a:65:2d:3a:9a:43:f8"]
-#       - attach_workspace:
-#           at: ~/ 
-#       - restore_cache: 
-#           keys: [backend-dependencies-ck]
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             cd backend
-#             npm install
-#       - run:
-#           name: Package backend
-#           command: |
-#             cd backend
-#             npm run build
-#             tar -czf artifact.tar.gz dist/* package*
+  deploy-backend:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_cli
+      - install_ansible
+      - install_nodejs
+      - add_ssh_keys:
+          fingerprints: ["3a:ac:7e:58:7d:53:2e:b4:b0:5a:65:2d:3a:9a:43:f8"]
+      - attach_workspace:
+          at: ~/ 
+      - restore_cache: 
+          keys: [backend-dependencies-ck]
+      - run:
+          name: Install dependencies
+          command: |
+            cd backend
+            npm install
+      - run:
+          name: Package backend
+          command: |
+            cd backend
+            npm run build
+            tar -czf artifact.tar.gz dist/* package*
 
-#             cd ..
-#             cp backend/artifact.tar.gz .circleci/ansible
-#       - run:
-#           name: Deploy backend
-#           command: |
-#             export TYPEORM_MIGRATIONS_DIR=./migrations
-#             export TYPEORM_ENTITIES=./modules/domain/**/*.entiry{.ts,.js}
-#             export TYPEORM_MIGRATIONS=./migrations/*.ts
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible
+      - run:
+          name: Deploy backend
+          command: |
+            export TYPEORM_MIGRATIONS_DIR=./migrations
+            export TYPEORM_ENTITIES=./modules/domain/**/*.entiry{.ts,.js}
+            export TYPEORM_MIGRATIONS=./migrations/*.ts
 
-#             cd .circleci/ansible
-#             cat inventory.txt
-#             ansible-playbook -i inventory.txt deploy-backend.yml
+            cd .circleci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
             
-#       - destroy-environment
-#       - revert-migrations  
-#   smoke-test:
-#     docker:
-#       - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations  
+  smoke-test:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_cli
+      - install_nodejs
+      - run:
+          name: Backend smoke test
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            
+            export API_URL=http://${BACKEND_PUBLIC_IP}::3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - run:
+          name: FrontEnd smoke test
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            
+            export API_URL=http://${BACKEND_PUBLIC_IP}::3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
 #   cloudfront-update:
 #     docker:
